- ESP32_OWM_Current_Forecast_29_epaper_v6.ino
code says ESP sleeps for milliseconds when should say microseconds
> code says ESP sleeps for milliseconds when should say microseconds

- ESP32_OWM_Current_Forecast_29_epaper_v7.ino
- README.md
Basically c&p from the 7.5" versions and double checked on my epaper - works for me.
Not sure if you want to rename the *.ino file to reflect the new version.
> 2.9" epaper version use ArduinoJSON v6

- ESP32_OWM_Current_Forecast_42_epaper_v11.ino
- README.md
Again, basically c&p from the 7.5" versions. Compiles for me and I did not see any benefit in 1. unrolling the loop, 2. calculating the pressure trend differently and dropping a few lines from the received json; In one of the next steps I would extract this part to a separate file.
> 4.2" epaper version use ArduinoJSON v6

- examples/ESP32_OWM_Current_Forecast_29_epaper_v7/ESP32_OWM_Current_Forecast_29_epaper_v7.ino
- examples/ESP32_OWM_Current_Forecast_42_epaper_v11/ESP32_OWM_Current_Forecast_42_epaper_v11.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v10/ESP32_OWM_Current_Forecast_75_epaper_v10.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v10a/ESP32_OWM_Current_Forecast_75_epaper_v10a.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v8/ESP32_OWM_Current_Forecast_75_epaper_v8.ino
- examples/French/ESP32_OWM_Current_Forecast_75_epaper_v8/ESP32_OWM_Current_Forecast_75_epaper_v8.ino
- examples/German/ESP32_OWM_Current_Forecast_Streaming_75_epaper_v3/ESP32_OWM_Current_Forecast_Streaming_75_epaper_v3.ino
- src/common.h
- src/forecast_record.h
As announced last time this is a first step towards a common code base
for all displays.
Of course this is far from being a nice seperation and modularization,
but it already helps to reduce the amount of lines drastically.
> Use common code for decoding weather

- examples/ESP32_OWM_Current_Forecast_29_epaper_v7/ESP32_OWM_Current_Forecast_29_epaper_v7.ino
- examples/ESP32_OWM_Current_Forecast_42_epaper_v11/ESP32_OWM_Current_Forecast_42_epaper_v11.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v10/ESP32_OWM_Current_Forecast_75_epaper_v10.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v10a/ESP32_OWM_Current_Forecast_75_epaper_v10a.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v11/ESP32_OWM_Current_Forecast_75_epaper_v11.ino
- src/common.h
Moved the juliandate, SumOfPercip and the convertunixtime function to the common part.
> Move common functions to common

- src/common.h
Instead of doing the bare HTTP commands yourself, you could use the
ESP32 (and ESP8266) HTTPClient implementation.
The advantages are
- returns a proper error message on failure
- less and more cosise code
However, there are few things I would put up for discussion.
I skipped the line setting the UserAgent, do you want it back?
There are two timeouts you can set of HTTPClient, setTimeout and
setConnectTimeout (see [this
PR](https://github.com/espressif/arduino-esp32/pull/2606)). If you
understood the code correctly, the former is closer to the your original
code (i.e. connection already established, time out on slow server
response), while the latter seems more appropriate imo (i.e. time out on
no connection).
Quick remark, the default timeout for the former is exactly the 5000ms
you had …
> HTTPClient for OWM data

- src/common.h
Reverts G6EJD/ESP32-e-Paper-Weather-Display#46
Not compiling too many errors
> Revert "HTTPClient for OWM data"

- src/common.h
Already deleted my other old branch and in this case Github doesn't allow to reopen the PR...
> Use HTTPClient

- examples/ESP32_OWM_Current_Forecast_29_epaper_v7/ESP32_OWM_Current_Forecast_29_epaper_v7.ino
- examples/ESP32_OWM_Current_Forecast_42_epaper_v11/ESP32_OWM_Current_Forecast_42_epaper_v11.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v10/ESP32_OWM_Current_Forecast_75_epaper_v10.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v10a/ESP32_OWM_Current_Forecast_75_epaper_v10a.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v11/ESP32_OWM_Current_Forecast_75_epaper_v11.ino
- src/common.h
- src/common_functions.cpp
- src/common_functions.h
Formerly there were basically two implementations of the moon phase. I
unified them to one which relies on the explicit julian date
calculation.
I also clean up some things on the way and discovered a bug for our
friends from the southern hemisphere :-)
I also resolved the warning (as error) in the HTTPClient implementation - Hope I found the correct spot.
> Unified moon phase calculation

- examples/ESP32_OWM_Current_Forecast_75_epaper_v10/ESP32_OWM_Current_Forecast_75_epaper_v10.ino
- examples/ESP32_OWM_Current_Forecast_75_epaper_v10a/ESP32_OWM_Current_Forecast_75_epaper_v10a.ino
Sorry, overlooked the three lines.
The CI would have told me... but I looked at only after the merge. Sorry about that.
> Bugfix: hemisphere

- examples/Waveshare_4_2/Waveshare_4_2.ino
- examples/Waveshare_7_5/Waveshare_7_5.ino
- Fix overwritten 7.5" patch
- Fix 4.2" Sunrise variable
fixes https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/issues/61
and https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/issues/60
> Reindroduce fixes, fixed 4_2 Sunrise

- examples/Waveshare_7_5/Waveshare_7_5.ino
as mentioned in https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/issues/60
> More overwritten changes

- examples/Waveshare_4_2/Waveshare_4_2.ino
- examples/Waveshare_7_5/Waveshare_7_5.ino
> Actual fix of 4.2

- examples/OWM_75_epaper_v16_7/OWM_75_epaper_v16_7.ino
- examples/Waveshare_2_9/Waveshare_2_9.ino
- examples/Waveshare_4_2/Waveshare_4_2.ino
- examples/Waveshare_7_5/Waveshare_7_5.ino
- src/lang.h
- src/lang_cz.h
- src/lang_es.h
- src/lang_fr.h
- src/lang_gr.h
- src/lang_it.h
This pull request will add czech localization. Czech localization also requires extended fonts (_te), so I introduces a macro FONT() that will select a correct variant of font.
> Added czech localization

- examples/OWM_75_epaper_v16_7/OWM_75_epaper_v16_7.ino
- examples/Waveshare_2_9/Waveshare_2_9.ino
- examples/Waveshare_4_2/Waveshare_4_2.ino
- examples/Waveshare_7_5/Waveshare_7_5.ino
- src/lang_nl.h
> Add Dutch translation (NL)

- examples/Waveshare_2_7/Waveshare_2_7.ino
- src/lang_gr.h
I added the Waveshare 2.7 Display
> Waveshare 2.7 Display

- src/lang_pt.h
> Portuguese language

- examples/Waveshare_2_13_T5/Waveshare_2_13_T5.ino
> typo in comment

- examples/Waveshare_2_7/owm_credentials.h
- examples/Waveshare_2_9_T5/Waveshare_2_9_T5.ino
Just for practice I tired to build all of the examples, this PR fixes the two that didn't build.
I don't have those displays so I didn't actually run the code, but at least they build now.
73's Skip WB6YMH
> Example build fixes

- Waveshare_2_9_v4.ino
- examples/M5_CoreInk/M5_CoreInk.ino
- examples/Waveshare_1_54/Waveshare_1_54.ino
- examples/Waveshare_2_9/Waveshare_2_9_v4.ino
- examples/Waveshare_4_2/Waveshare_4_2.ino
- examples/Waveshare_7_5/Waveshare_7_5.ino
- examples/Waveshare_7_5_T7/Waveshare_7_5_T7.ino
- examples/Waveshare_9_7/Waveshare_9_7.ino
WxForecast[].Timezone is never set, hence WxConditions[0].Timezone must be used as it was in the original code.
> Revert WxConditions[0].Timezone -> WxForecast[index].Timezone, it wasn't wrong.

- examples/Waveshare_3_7/Waveshare_3_7.ino
It looks like I really messed up the sleep timer code in the original commit when I tried to add the 'overnight long sleep'.
Rewrite that code, to cater for both big sleeps that start either before or after midnight.
Whilst there, make the SleepDuration/WakeupTime/SleepTime variables consts, which specifically in this new code allows the compiler to drop out the case that we are obviously not using. In my local tests this dropped ~100bytes from the image size (and probably saved us a single bit of math/test in the code itself).
Fixes: #217
> WS_3_7: Fix sleep timer code
